# Generated by Coalesce

def add(a, b):
    return a + b

def calculateArea(radius):
    return 3.14159 * radius * radius

# Test the functions
if __name__ == "__main__":
    print("Testing generated Python code:")
    print(f"add(5, 3) = {add(5, 3)}")
    print(f"calculateArea(2) = {calculateArea(2)}")
