// Generated by Coalesce

fn add(a: i32, b: i32) -> i32 {
    a + b
}

fn calculate_area(radius: f64) -> f64 {
    3.14159 * radius * radius
}

fn main() {
    println!("Testing generated Rust code:");
    println!("add(5, 3) = {}", add(5, 3));
    println!("calculate_area(2.0) = {}", calculate_area(2.0));
}
